# Generated by Django 4.1.3 on 2023-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='item',
        ),
    ]
